project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://blog.wndlng.ch
  title: "jwndlng.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://www.github.com/jwndlng
      - icon: linkedin
        href: https://www.linkedin.com/in/jan-wendling/
format:
  html:
    theme: none
    highlight-style: arrow
    css:
      - https://cdn.jsdelivr.net/gh/edwardtufte/tufte-css@gh-pages/tufte.css
      - styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">



