project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://blog.wndlng.ch
  title: "jwndlng.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://www.github.com/jwndlng
      - icon: linkedin
        href: https://www.linkedin.com/in/jan-wendling/
format:
  tufte-html:
    highlight-style: arrow
    css: styles.css



