---

base:
  author: Jan Wendling
  contact: jan.wendling@gmail.com
  timezone: 'Europe/Zurich'
  content: raw
pages:
  index:
    title: 'Welcome to wndlng.github.io!'
    name: 'About'
    type: default
  posts:
    title: 'Posts'
    name: 'My Posts'
    pagination: 10
    type: article
  projects:
    title: 'Projects'
    name: 'My Projects'
    pagination: 10
    type: article
templates:
  nav: nav
  article: page_article
  default: default
social_media:
  github: github.com/jwndlng
  gitlab:
  linkedin:
