---

base:
  author: Jan Wendling
  contact: jan.wendling@gmail.com
  timezone: 'Europe/Zurich'
  content: raw
pages:
  - file: index
    name: 'About'
    nav: [main]
    title: 'Welcome to jwndlng.github.io!'
    type: default
  - file: posts
    name: 'My Posts'
    nav: [main]
    pagination: 10
    title: 'Posts'
    type: article
  - file: projects   
    name: 'My Projects'
    nav: [main]
    pagination: 10
    title: 'Projects'
    type: article
  - file: imprint
    name: 'Imprint'
    nav: [footer]
    pagination: 10
    title: 'Imprint'
    type: default
templates:
  nav: nav
  article: page_article
  default: default
social_media:
  github:
    title: GitHub
    href: https://github.com/jwndlng
  gitlab:
    title: GitLab
    href: https://gitlab.com/jwndlng
  linkedin:
    title: LinkedIn
    href: https://linkedin.com/jan-wendling
