---

base:
  author: Jan Wendling
  contact: jan.wendling@gmail.com
  timezone: 'Europe/Zurich'
  content: raw
pages:
  home:
    title: 'Welcome to wndlng.github.io!'
    type: default
  posts:
    title: 'Posts'
    pagination: 10
    type: article
  projects:
    title: 'Projects'
    pagination: 10
    type: article
social_media:
  github: github.com/jwndlng
  gitlab:
  linkedin:
